#Sound Effects for song Untitled, version 2.0, generated by Arkos Tracker 2.

Ep1_SoundEffects:
Ep1_SoundEffectsDisarkGenerateExternalLabel:

#The sound effects, starting at 1.
Ep1_SoundEffectsDisarkPointerRegionStart0:
	.word Ep1_SoundEffects_Sound1	#Sound effect 1.
	.word Ep1_SoundEffects_Sound2	#Sound effect 2.
	.word Ep1_SoundEffects_Sound3	#Sound effect 3.
	.word Ep1_SoundEffects_Sound4	#Sound effect 4.
	.word Ep1_SoundEffects_Sound5	#Sound effect 5.
	.word Ep1_SoundEffects_Sound6	#Sound effect 6.
	.word Ep1_SoundEffects_Sound7	#Sound effect 7.
Ep1_SoundEffectsDisarkPointerRegionEnd0:

Ep1_SoundEffectsDisarkByteRegionStart1:
#Sound effect 1.
Ep1_SoundEffects_Sound1:
	.byte 0	#Speed

Ep1_SoundEffects_Sound1_Loop:	.byte 61	#Soft only. Volume: 15.
	.word 239	#Software period.

	.byte 4	#End of the sound effect.

#Sound effect 2.
Ep1_SoundEffects_Sound2:
	.byte 0	#Speed

Ep1_SoundEffects_Sound2_Loop:	.byte 189	#Soft only. Volume: 15.
	.byte 6	#Noise: 6.
	.word 119	#Software period.

	.byte 185	#Soft only. Volume: 14.
	.byte 5	#Noise: 5.
	.word 113	#Software period.

	.byte 169	#Soft only. Volume: 10.
	.byte 1	#Noise: 1.
	.word 95	#Software period.

	.byte 17	#Soft only. Volume: 4.
	.word 142	#Software period.

	.byte 4	#End of the sound effect.

#Sound effect 3.
Ep1_SoundEffects_Sound3:
	.byte 0	#Speed

Ep1_SoundEffects_Sound3_Loop:	.byte 248	#No soft, no hard. Volume: 15.
	.byte 6	#Noise: 6.

	.byte 240	#No soft, no hard. Volume: 14.
	.byte 12	#Noise: 12.

	.byte 232	#No soft, no hard. Volume: 13.
	.byte 12	#Noise: 12.

	.byte 192	#No soft, no hard. Volume: 8.
	.byte 12	#Noise: 12.

	.byte 160	#No soft, no hard. Volume: 4.
	.byte 4	#Noise: 4.

	.byte 4	#End of the sound effect.

#Sound effect 4.
Ep1_SoundEffects_Sound4:
	.byte 0	#Speed

Ep1_SoundEffects_Sound4_Loop:	.byte 189	#Soft only. Volume: 15.
	.byte 10	#Noise: 10.
	.word 179	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 18	#Noise: 18.
	.word 150	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 12	#Noise: 12.
	.word 142	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 8	#Noise: 8.
	.word 150	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 5	#Noise: 5.
	.word 159	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 3	#Noise: 3.
	.word 169	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 5	#Noise: 5.
	.word 179	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 7	#Noise: 7.
	.word 190	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 5	#Noise: 5.
	.word 201	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 3	#Noise: 3.
	.word 213	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 1	#Noise: 1.
	.word 225	#Software period.

	.byte 185	#Soft only. Volume: 14.
	.byte 1	#Noise: 1.
	.word 239	#Software period.

	.byte 173	#Soft only. Volume: 11.
	.byte 1	#Noise: 1.
	.word 253	#Software period.

	.byte 161	#Soft only. Volume: 8.
	.byte 1	#Noise: 1.
	.word 268	#Software period.

	.byte 153	#Soft only. Volume: 6.
	.byte 1	#Noise: 1.
	.word 284	#Software period.

	.byte 17	#Soft only. Volume: 4.
	.word 301	#Software period.

	.byte 9	#Soft only. Volume: 2.
	.word 319	#Software period.

	.byte 4	#End of the sound effect.

#Sound effect 5.
Ep1_SoundEffects_Sound5:
	.byte 2	#Speed

Ep1_SoundEffects_Sound5_Loop:	.byte 189	#Soft only. Volume: 15.
	.byte 17	#Noise: 17.
	.word 38	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 25	#Noise: 25.
	.word 71	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 31	#Noise: 31.
	.word 95	#Software period.

	.byte 189	#Soft only. Volume: 15.
	.byte 24	#Noise: 24.
	.word 179	#Software period.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 16	#Noise: 16.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 25	#Noise: 25.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 31	#Noise: 31.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 24	#Noise: 24.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 14	#Noise: 14.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 26	#Noise: 26.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 31	#Noise: 31.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 25	#Noise: 25.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 13	#Noise: 13.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 24	#Noise: 24.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 31	#Noise: 31.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 21	#Noise: 21.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 13	#Noise: 13.

	.byte 248	#No soft, no hard. Volume: 15.
	.byte 21	#Noise: 21.

	.byte 224	#No soft, no hard. Volume: 12.
	.byte 31	#Noise: 31.

	.byte 192	#No soft, no hard. Volume: 8.
	.byte 22	#Noise: 22.

	.byte 168	#No soft, no hard. Volume: 5.
	.byte 12	#Noise: 12.

	.byte 32	#No soft, no hard. Volume: 4.

	.byte 16	#No soft, no hard. Volume: 2.

	.byte 4	#End of the sound effect.

#Sound effect 6.
Ep1_SoundEffects_Sound6:
	.byte 0	#Speed

Ep1_SoundEffects_Sound6_Loop:	.byte 61	#Soft only. Volume: 15.
	.word 239	#Software period.

	.byte 61	#Soft only. Volume: 15.
	.word 95	#Software period.

	.byte 4	#End of the sound effect.

#Sound effect 7.
Ep1_SoundEffects_Sound7:
	.byte 1	#Speed

Ep1_SoundEffects_Sound7_Loop:	.byte 179	#Soft and Hard. Env: 14.
	.byte 21	#Noise: 21.
	.word 239	#Hardware period.
	.word 602	#Software period.

	.byte 179	#Soft and Hard. Env: 14.
	.byte 11	#Noise: 11.
	.word 239	#Hardware period.
	.word 319	#Software period.

	.byte 179	#Soft and Hard. Env: 14.
	.byte 3	#Noise: 3.
	.word 239	#Hardware period.
	.word 239	#Software period.

	.byte 51	#Soft and Hard. Env: 14.
	.word 239	#Hardware period.
	.word 225	#Software period.

	.byte 51	#Soft and Hard. Env: 14.
	.word 239	#Hardware period.
	.word 213	#Software period.

	.byte 4	#End of the sound effect.

Ep1_SoundEffectsDisarkByteRegionEnd1:
