#Ep1 Title Music, AKG format, v1.0.

#Generated by Arkos Tracker 2.

Ep1TitleMusic_Start:
Ep1TitleMusic_StartDisarkGenerateExternalLabel:

Ep1TitleMusic_DisarkByteRegionStart0:
	.ascii "AT20"
Ep1TitleMusic_DisarkPointerRegionStart1:
	.word Ep1TitleMusic_ArpeggioTable	#The address of the Arpeggio table.
	.word Ep1TitleMusic_PitchTable	#The address of the Pitch table.
	.word Ep1TitleMusic_InstrumentTable	#The address of the Instrument table.
	.word Ep1TitleMusic_EffectBlockTable	#The address of the Effect Block table.
Ep1TitleMusic_DisarkPointerRegionEnd1:


#The addresses of each Subsong:
Ep1TitleMusic_DisarkPointerRegionStart2:
	.word Ep1TitleMusic_Subsong0_Start
Ep1TitleMusic_DisarkPointerRegionEnd2:

#Declares all the Arpeggios.
Ep1TitleMusic_ArpeggioTable:
Ep1TitleMusic_DisarkPointerRegionStart3:
Ep1TitleMusic_DisarkPointerRegionEnd3:

#Declares all the Pitches.
Ep1TitleMusic_PitchTable:
Ep1TitleMusic_DisarkPointerRegionStart4:
Ep1TitleMusic_DisarkPointerRegionEnd4:

#Declares all the Instruments.
Ep1TitleMusic_InstrumentTable:
Ep1TitleMusic_DisarkPointerRegionStart5:
	.word Ep1TitleMusic_EmptyInstrument
	.word Ep1TitleMusic_Instrument1
	.word Ep1TitleMusic_Instrument2
	.word Ep1TitleMusic_Instrument3
	.word Ep1TitleMusic_Instrument4
	.word Ep1TitleMusic_Instrument5
	.word Ep1TitleMusic_Instrument6
	.word Ep1TitleMusic_Instrument7
	.word Ep1TitleMusic_Instrument8
Ep1TitleMusic_DisarkPointerRegionEnd5:

Ep1TitleMusic_EmptyInstrument:
	.byte 0	#The speed (>0, 0 for 256).
Ep1TitleMusic_EmptyInstrument_Loop:	.byte 0	#No Soft no Hard. Volume: 0. Noise? false.

	.byte 6	#Loop to silence.

Ep1TitleMusic_Instrument1:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 121	#Soft only. Volume: 15.
	.byte 78	#Additional data. Noise: 14. Pitch? false. Arp? true. Period? false.
	.byte 5	#Arpeggio.

	.byte 121	#Soft only. Volume: 15.
	.byte 70	#Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	.byte 3	#Arpeggio.

	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 121	#Soft only. Volume: 15.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -5	#Arpeggio.

	.byte 113	#Soft only. Volume: 14.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -10	#Arpeggio.

	.byte 113	#Soft only. Volume: 14.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -10	#Arpeggio.

	.byte 97	#Soft only. Volume: 12.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -15	#Arpeggio.

	.byte 97	#Soft only. Volume: 12.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -15	#Arpeggio.

	.byte 97	#Soft only. Volume: 12.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -15	#Arpeggio.

	.byte 89	#Soft only. Volume: 11.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -15	#Arpeggio.

	.byte 73	#Soft only. Volume: 9.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -15	#Arpeggio.

	.byte 169	#Soft only. Volume: 5. Volume only.

	.byte 6	#Loop to silence.

Ep1TitleMusic_Instrument2:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 121	#Soft only. Volume: 15.
	.byte 105	#Additional data. Noise: 9. Pitch? true. Arp? true. Period? false.
	.byte 126	#Arpeggio.
	.word -9	#Pitch.

	.byte 121	#Soft only. Volume: 15.
	.byte 71	#Additional data. Noise: 7. Pitch? false. Arp? true. Period? false.
	.byte 82	#Arpeggio.

	.byte 121	#Soft only. Volume: 15.
	.byte 70	#Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	.byte 124	#Arpeggio.

	.byte 121	#Soft only. Volume: 15.
	.byte 69	#Additional data. Noise: 5. Pitch? false. Arp? true. Period? false.
	.byte 85	#Arpeggio.

	.byte 113	#Soft only. Volume: 14.
	.byte 4	#Additional data. Noise: 4. Pitch? false. Arp? false. Period? false.

	.byte 97	#Soft only. Volume: 12.
	.byte 3	#Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

	.byte 81	#Soft only. Volume: 10.
	.byte 2	#Additional data. Noise: 2. Pitch? false. Arp? false. Period? false.

	.byte 65	#Soft only. Volume: 8.
	.byte 1	#Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	.byte 177	#Soft only. Volume: 6. Volume only.

	.byte 177	#Soft only. Volume: 6. Volume only.

	.byte 6	#Loop to silence.

Ep1TitleMusic_Instrument3:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 224	#No Soft no Hard. Volume: 12. Noise? true.
	.byte 1	#Noise: 1.

	.byte 6	#Loop to silence.

Ep1TitleMusic_Instrument4:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 105	#Soft only. Volume: 13.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 1	#Arpeggio.

	.byte 121	#Soft only. Volume: 15.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 1	#Arpeggio.

	.byte 209	#Soft only. Volume: 10. Volume only.

	.byte 233	#Soft only. Volume: 13. Volume only.

	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 209	#Soft only. Volume: 10. Volume only.

	.byte 193	#Soft only. Volume: 8. Volume only.

	.byte 177	#Soft only. Volume: 6. Volume only.

	.byte 161	#Soft only. Volume: 4. Volume only.

	.byte 6	#Loop to silence.

Ep1TitleMusic_Instrument5:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 121	#Soft only. Volume: 15.
	.byte 3	#Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

	.byte 121	#Soft only. Volume: 15.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 6	#Arpeggio.

	.byte 121	#Soft only. Volume: 15.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 4	#Arpeggio.

	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 121	#Soft only. Volume: 15.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 6	#Arpeggio.

	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 201	#Soft only. Volume: 9. Volume only.

	.byte 6	#Loop to silence.

Ep1TitleMusic_Instrument6:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 6	#Loop to silence.

Ep1TitleMusic_Instrument7:
	.byte 1	#The speed (>0, 0 for 256).
Ep1TitleMusic_Instrument7_Loop:	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 7	#Loop.
Ep1TitleMusic_DisarkWordForceReference6:
	.word Ep1TitleMusic_Instrument7_Loop	#Loop here.

Ep1TitleMusic_Instrument8:
	.byte 1	#The speed (>0, 0 for 256).
Ep1TitleMusic_Instrument8_Loop:	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 121	#Soft only. Volume: 15.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 6	#Arpeggio.

	.byte 121	#Soft only. Volume: 15.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 4	#Arpeggio.

	.byte 7	#Loop.
Ep1TitleMusic_DisarkWordForceReference7:
	.word Ep1TitleMusic_Instrument8_Loop	#Loop here.


#The indexes of the effect blocks used by this song.
Ep1TitleMusic_EffectBlockTable:
Ep1TitleMusic_DisarkPointerRegionStart8:
	.word Ep1TitleMusic_EffectBlock_P4P0	#Index 0
	.word Ep1TitleMusic_EffectBlock_P20P26P1	#Index 1
	.word Ep1TitleMusic_EffectBlock_P20P57P0	#Index 2
	.word Ep1TitleMusic_EffectBlock_P20P88P1	#Index 3
	.word Ep1TitleMusic_EffectBlock_P20P115P0	#Index 4
	.word Ep1TitleMusic_EffectBlock_P20P145P1	#Index 5
	.word Ep1TitleMusic_EffectBlock_P20P172P0	#Index 6
	.word Ep1TitleMusic_EffectBlock_P20P202P1	#Index 7
	.word Ep1TitleMusic_EffectBlock_P20P229P0	#Index 8
	.word Ep1TitleMusic_EffectBlock_P4P3	#Index 9
	.word Ep1TitleMusic_EffectBlock_P4P5	#Index 10
	.word Ep1TitleMusic_EffectBlock_P4P9	#Index 11
Ep1TitleMusic_DisarkPointerRegionEnd8:

Ep1TitleMusic_EffectBlock_P4P0:
	.byte 4, 0
Ep1TitleMusic_EffectBlock_P4P3:
	.byte 4, 3
Ep1TitleMusic_EffectBlock_P4P5:
	.byte 4, 5
Ep1TitleMusic_EffectBlock_P4P9:
	.byte 4, 9
Ep1TitleMusic_EffectBlock_P20P26P1:
	.byte 20, 26, 1
Ep1TitleMusic_EffectBlock_P20P57P0:
	.byte 20, 57, 0
Ep1TitleMusic_EffectBlock_P20P88P1:
	.byte 20, 88, 1
Ep1TitleMusic_EffectBlock_P20P115P0:
	.byte 20, 115, 0
Ep1TitleMusic_EffectBlock_P20P145P1:
	.byte 20, 145, 1
Ep1TitleMusic_EffectBlock_P20P172P0:
	.byte 20, 172, 0
Ep1TitleMusic_EffectBlock_P20P202P1:
	.byte 20, 202, 1
Ep1TitleMusic_EffectBlock_P20P229P0:
	.byte 20, 229, 0

Ep1TitleMusic_DisarkByteRegionEnd0:

#Subsong 0
#----------------------
Ep1TitleMusic_Subsong0_DisarkByteRegionStart0:
Ep1TitleMusic_Subsong0_Start:
	.byte 2	#ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	.byte 0	#Digichannel (0-2).
	.byte 1	#PSG count (>0).
	.byte 0	#Loop start index (>=0).
	.byte 29	#End index (>=0).
	.byte 6	#Initial speed (>=0).
	.byte 0	#Base note index (>=0).

Ep1TitleMusic_Subsong0_Linker:
Ep1TitleMusic_Subsong0_DisarkPointerRegionStart1:
#Position 0
Ep1TitleMusic_Subsong0_Linker_Loop:
	.word Ep1TitleMusic_Subsong0_Track0
	.word Ep1TitleMusic_Subsong0_Track4
	.word Ep1TitleMusic_Subsong0_Track0
	.word Ep1TitleMusic_Subsong0_LinkerBlock0

#Position 1
	.word Ep1TitleMusic_Subsong0_Track0
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track0
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 2
	.word Ep1TitleMusic_Subsong0_Track0
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track0
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 3
	.word Ep1TitleMusic_Subsong0_Track10
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track3
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 4
	.word Ep1TitleMusic_Subsong0_Track16
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 5
	.word Ep1TitleMusic_Subsong0_Track1
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 6
	.word Ep1TitleMusic_Subsong0_Track1
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 7
	.word Ep1TitleMusic_Subsong0_Track2
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 8
	.word Ep1TitleMusic_Subsong0_Track7
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 9
	.word Ep1TitleMusic_Subsong0_Track8
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 10
	.word Ep1TitleMusic_Subsong0_Track8
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 11
	.word Ep1TitleMusic_Subsong0_Track9
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 12
	.word Ep1TitleMusic_Subsong0_Track9
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 13
	.word Ep1TitleMusic_Subsong0_Track1
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 14
	.word Ep1TitleMusic_Subsong0_Track1
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 15
	.word Ep1TitleMusic_Subsong0_Track2
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 16
	.word Ep1TitleMusic_Subsong0_Track7
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 17
	.word Ep1TitleMusic_Subsong0_Track8
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 18
	.word Ep1TitleMusic_Subsong0_Track8
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 19
	.word Ep1TitleMusic_Subsong0_Track9
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 20
	.word Ep1TitleMusic_Subsong0_Track9
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 21
	.word Ep1TitleMusic_Subsong0_Track1
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 22
	.word Ep1TitleMusic_Subsong0_Track1
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 23
	.word Ep1TitleMusic_Subsong0_Track2
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 24
	.word Ep1TitleMusic_Subsong0_Track7
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 25
	.word Ep1TitleMusic_Subsong0_Track8
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 26
	.word Ep1TitleMusic_Subsong0_Track8
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 27
	.word Ep1TitleMusic_Subsong0_Track9
	.word Ep1TitleMusic_Subsong0_Track5
	.word Ep1TitleMusic_Subsong0_Track6
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 28
	.word Ep1TitleMusic_Subsong0_Track11
	.word Ep1TitleMusic_Subsong0_Track15
	.word Ep1TitleMusic_Subsong0_Track14
	.word Ep1TitleMusic_Subsong0_LinkerBlock1

#Position 29
	.word Ep1TitleMusic_Subsong0_Track12
	.word Ep1TitleMusic_Subsong0_Track13
	.word Ep1TitleMusic_Subsong0_Track12
	.word Ep1TitleMusic_Subsong0_LinkerBlock2

Ep1TitleMusic_Subsong0_DisarkPointerRegionEnd1:
	.word 0	#Loop.
Ep1TitleMusic_Subsong0_DisarkWordForceReference2:
	.word Ep1TitleMusic_Subsong0_Linker_Loop

Ep1TitleMusic_Subsong0_LinkerBlock0:
	.byte 24	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
Ep1TitleMusic_Subsong0_DisarkWordForceReference3:
	.word Ep1TitleMusic_Subsong0_SpeedTrack0	#SpeedTrack address.
Ep1TitleMusic_Subsong0_DisarkWordForceReference4:
	.word Ep1TitleMusic_Subsong0_EventTrack0	#EventTrack address.
Ep1TitleMusic_Subsong0_LinkerBlock1:
	.byte 32	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
Ep1TitleMusic_Subsong0_DisarkWordForceReference5:
	.word Ep1TitleMusic_Subsong0_SpeedTrack0	#SpeedTrack address.
Ep1TitleMusic_Subsong0_DisarkWordForceReference6:
	.word Ep1TitleMusic_Subsong0_EventTrack0	#EventTrack address.
Ep1TitleMusic_Subsong0_LinkerBlock2:
	.byte 1	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
Ep1TitleMusic_Subsong0_DisarkWordForceReference7:
	.word Ep1TitleMusic_Subsong0_SpeedTrack0	#SpeedTrack address.
Ep1TitleMusic_Subsong0_DisarkWordForceReference8:
	.word Ep1TitleMusic_Subsong0_EventTrack0	#EventTrack address.

Ep1TitleMusic_Subsong0_Track0:
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track1:
	.byte 236
	.byte 5	#New Instrument (5).
	.byte 0	#Index to an effect block.
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 44
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 45
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 45
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 44
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 44
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 45
	.byte 45
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track2:
	.byte 173
	.byte 5	#New Instrument (5).
	.byte 60	#Waits for 1 line.

	.byte 44
	.byte 45
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 45
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 44
	.byte 45
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 44
	.byte 60	#Waits for 1 line.

	.byte 44
	.byte 45
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track3:
	.byte 61, 23	#Waits for 24 lines.

	.byte 140
	.byte 2	#New Instrument (2).
	.byte 12
	.byte 60	#Waits for 1 line.

	.byte 12
	.byte 12
	.byte 60	#Waits for 1 line.

	.byte 12
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track4:
	.byte 140
	.byte 7	#New Instrument (7).
	.byte 61, 6	#Waits for 7 lines.

	.byte 14
	.byte 61, 6	#Waits for 7 lines.

	.byte 16
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track5:
	.byte 142
	.byte 4	#New Instrument (4).
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 17
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 16
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 16
	.byte 14
	.byte 12
	.byte 14
	.byte 16
	.byte 14
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track6:
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 24
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track7:
	.byte 173
	.byte 5	#New Instrument (5).
	.byte 60	#Waits for 1 line.

	.byte 44
	.byte 45
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 45
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 44
	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 43
	.byte 44
	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 45
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track8:
	.byte 173
	.byte 5	#New Instrument (5).
	.byte 60	#Waits for 1 line.

	.byte 44
	.byte 45
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 45
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 44
	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 43
	.byte 44
	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track9:
	.byte 170
	.byte 5	#New Instrument (5).
	.byte 60	#Waits for 1 line.

	.byte 42
	.byte 42
	.byte 42
	.byte 60	#Waits for 1 line.

	.byte 40
	.byte 38
	.byte 37
	.byte 60	#Waits for 1 line.

	.byte 37
	.byte 37
	.byte 37
	.byte 60	#Waits for 1 line.

	.byte 40
	.byte 41
	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 43
	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 40
	.byte 40
	.byte 42
	.byte 60	#Waits for 1 line.

	.byte 42
	.byte 42
	.byte 42
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track10:
	.byte 237
	.byte 5	#New Instrument (5).
	.byte 11	#Index to an effect block.
	.byte 61, 6	#Waits for 7 lines.

	.byte 109
	.byte 10	#Index to an effect block.
	.byte 61, 6	#Waits for 7 lines.

	.byte 109
	.byte 9	#Index to an effect block.
	.byte 61, 6	#Waits for 7 lines.

	.byte 45
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track11:
	.byte 173
	.byte 5	#New Instrument (5).
	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 44
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 46
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 237
	.byte 8	#New Instrument (8).
	.byte 2	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 4	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 6	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 8	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 1	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 3	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 5	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 7	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track12:
	.byte 152
	.byte 1	#New Instrument (1).
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track13:
	.byte 152
	.byte 6	#New Instrument (6).
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track14:
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 2	#New Instrument (2).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 158
	.byte 1	#New Instrument (1).
	.byte 140
	.byte 3	#New Instrument (3).
	.byte 30
	.byte 152
	.byte 2	#New Instrument (2).
	.byte 24
	.byte 24
	.byte 24
	.byte 24
	.byte 24
	.byte 24
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track15:
	.byte 60	#Waits for 1 line.

	.byte 142
	.byte 4	#New Instrument (4).
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 17
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 16
	.byte 60	#Waits for 1 line.

	.byte 14
	.byte 60	#Waits for 1 line.

	.byte 159
	.byte 3	#New Instrument (3).
	.byte 31
	.byte 31
	.byte 31
	.byte 31
	.byte 31
	.byte 31
	.byte 61, 127	#Waits for 128 lines.


Ep1TitleMusic_Subsong0_Track16:
	.byte 237
	.byte 5	#New Instrument (5).
	.byte 0	#Index to an effect block.
	.byte 61, 6	#Waits for 7 lines.

	.byte 45
	.byte 61, 6	#Waits for 7 lines.

	.byte 45
	.byte 61, 6	#Waits for 7 lines.

	.byte 45
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 45
	.byte 43
	.byte 45
	.byte 61, 127	#Waits for 128 lines.


#The speed tracks
Ep1TitleMusic_Subsong0_SpeedTrack0:
	.byte 255	#Wait for 128 lines.

#The event tracks
Ep1TitleMusic_Subsong0_EventTrack0:
	.byte 255	#Wait for 128 lines.

Ep1TitleMusic_Subsong0_DisarkByteRegionEnd0:
