#Untitled, AKG format, v1.0.

#Generated by Arkos Tracker 2.

Ep1LevelMusic_Start:
Ep1LevelMusic_StartDisarkGenerateExternalLabel:

Ep1LevelMusic_DisarkByteRegionStart0:
	.ascii "AT20"
Ep1LevelMusic_DisarkPointerRegionStart1:
	.word Ep1LevelMusic_ArpeggioTable	#The address of the Arpeggio table.
	.word Ep1LevelMusic_PitchTable	#The address of the Pitch table.
	.word Ep1LevelMusic_InstrumentTable	#The address of the Instrument table.
	.word Ep1LevelMusic_EffectBlockTable	#The address of the Effect Block table.
Ep1LevelMusic_DisarkPointerRegionEnd1:


#The addresses of each Subsong:
Ep1LevelMusic_DisarkPointerRegionStart2:
	.word Ep1LevelMusic_Subsong0_Start
Ep1LevelMusic_DisarkPointerRegionEnd2:

#Declares all the Arpeggios.
Ep1LevelMusic_ArpeggioTable:
Ep1LevelMusic_DisarkPointerRegionStart3:
Ep1LevelMusic_DisarkPointerRegionEnd3:

#Declares all the Pitches.
Ep1LevelMusic_PitchTable:
Ep1LevelMusic_DisarkPointerRegionStart4:
Ep1LevelMusic_DisarkPointerRegionEnd4:

#Declares all the Instruments.
Ep1LevelMusic_InstrumentTable:
Ep1LevelMusic_DisarkPointerRegionStart5:
	.word Ep1LevelMusic_EmptyInstrument
	.word Ep1LevelMusic_Instrument1
	.word Ep1LevelMusic_Instrument2
	.word Ep1LevelMusic_Instrument3
	.word Ep1LevelMusic_Instrument4
	.word Ep1LevelMusic_Instrument5
	.word Ep1LevelMusic_Instrument6
Ep1LevelMusic_DisarkPointerRegionEnd5:

Ep1LevelMusic_EmptyInstrument:
	.byte 0	#The speed (>0, 0 for 256).
Ep1LevelMusic_EmptyInstrument_Loop:	.byte 0	#No Soft no Hard. Volume: 0. Noise? false.

	.byte 6	#Loop to silence.

Ep1LevelMusic_Instrument1:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 121	#Soft only. Volume: 15.
	.byte 1	#Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	.byte 121	#Soft only. Volume: 15.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 3	#Arpeggio.

	.byte 241	#Soft only. Volume: 14. Volume only.

	.byte 105	#Soft only. Volume: 13.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -5	#Arpeggio.

	.byte 97	#Soft only. Volume: 12.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -10	#Arpeggio.

	.byte 89	#Soft only. Volume: 11.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -10	#Arpeggio.

	.byte 81	#Soft only. Volume: 10.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte -15	#Arpeggio.

	.byte 6	#Loop to silence.

Ep1LevelMusic_Instrument2:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 121	#Soft only. Volume: 15.
	.byte 105	#Additional data. Noise: 9. Pitch? true. Arp? true. Period? false.
	.byte 126	#Arpeggio.
	.word -5	#Pitch.

	.byte 121	#Soft only. Volume: 15.
	.byte 71	#Additional data. Noise: 7. Pitch? false. Arp? true. Period? false.
	.byte 82	#Arpeggio.

	.byte 121	#Soft only. Volume: 15.
	.byte 70	#Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	.byte 124	#Arpeggio.

	.byte 121	#Soft only. Volume: 15.
	.byte 69	#Additional data. Noise: 5. Pitch? false. Arp? true. Period? false.
	.byte 85	#Arpeggio.

	.byte 121	#Soft only. Volume: 15.
	.byte 4	#Additional data. Noise: 4. Pitch? false. Arp? false. Period? false.

	.byte 113	#Soft only. Volume: 14.
	.byte 3	#Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

	.byte 105	#Soft only. Volume: 13.
	.byte 2	#Additional data. Noise: 2. Pitch? false. Arp? false. Period? false.

	.byte 113	#Soft only. Volume: 14.
	.byte 1	#Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 6	#Loop to silence.

Ep1LevelMusic_Instrument3:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 224	#No Soft no Hard. Volume: 12. Noise? true.
	.byte 1	#Noise: 1.

	.byte 6	#Loop to silence.

Ep1LevelMusic_Instrument4:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 232	#No Soft no Hard. Volume: 13. Noise? true.
	.byte 5	#Noise: 5.

	.byte 121	#Soft only. Volume: 15.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 1	#Arpeggio.

	.byte 209	#Soft only. Volume: 10. Volume only.

	.byte 233	#Soft only. Volume: 13. Volume only.

	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 209	#Soft only. Volume: 10. Volume only.

	.byte 193	#Soft only. Volume: 8. Volume only.

	.byte 177	#Soft only. Volume: 6. Volume only.

	.byte 161	#Soft only. Volume: 4. Volume only.

	.byte 153	#Soft only. Volume: 3. Volume only.

	.byte 137	#Soft only. Volume: 1. Volume only.

	.byte 137	#Soft only. Volume: 1. Volume only.

	.byte 6	#Loop to silence.

Ep1LevelMusic_Instrument5:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 6	#Loop to silence.

Ep1LevelMusic_Instrument6:
	.byte 1	#The speed (>0, 0 for 256).
Ep1LevelMusic_Instrument6_Loop:	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 7	#Loop.
Ep1LevelMusic_DisarkWordForceReference6:
	.word Ep1LevelMusic_Instrument6_Loop	#Loop here.


#The indexes of the effect blocks used by this song.
Ep1LevelMusic_EffectBlockTable:
Ep1LevelMusic_DisarkPointerRegionStart7:
	.word Ep1LevelMusic_EffectBlock_P5P15P20P0P1	#Index 0
	.word Ep1LevelMusic_EffectBlock_P5P5P20P32P0	#Index 1
	.word Ep1LevelMusic_EffectBlock_P4P0	#Index 2
	.word Ep1LevelMusic_EffectBlock_P20P128P0	#Index 3
	.word Ep1LevelMusic_EffectBlock_P20P160P0	#Index 4
	.word Ep1LevelMusic_EffectBlock_P20P192P0	#Index 5
	.word Ep1LevelMusic_EffectBlock_P20P224P0	#Index 6
	.word Ep1LevelMusic_EffectBlock_P20P64P0	#Index 7
	.word Ep1LevelMusic_EffectBlock_P20P96P0	#Index 8
	.word Ep1LevelMusic_EffectBlock_P4P15	#Index 9
Ep1LevelMusic_DisarkPointerRegionEnd7:

Ep1LevelMusic_EffectBlock_P4P0:
	.byte 4, 0
Ep1LevelMusic_EffectBlock_P5P15P20P0P1:
	.byte 5, 15, 20, 0, 1
Ep1LevelMusic_EffectBlock_P20P128P0:
	.byte 20, 128, 0
Ep1LevelMusic_EffectBlock_P20P160P0:
	.byte 20, 160, 0
Ep1LevelMusic_EffectBlock_P20P192P0:
	.byte 20, 192, 0
Ep1LevelMusic_EffectBlock_P20P224P0:
	.byte 20, 224, 0
Ep1LevelMusic_EffectBlock_P5P5P20P32P0:
	.byte 5, 5, 20, 32, 0
Ep1LevelMusic_EffectBlock_P20P64P0:
	.byte 20, 64, 0
Ep1LevelMusic_EffectBlock_P20P96P0:
	.byte 20, 96, 0
Ep1LevelMusic_EffectBlock_P4P15:
	.byte 4, 15

Ep1LevelMusic_DisarkByteRegionEnd0:

#Subsong 0
#----------------------
Ep1LevelMusic_Subsong0_DisarkByteRegionStart0:
Ep1LevelMusic_Subsong0_Start:
	.byte 2	#ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	.byte 0	#Digichannel (0-2).
	.byte 1	#PSG count (>0).
	.byte 0	#Loop start index (>=0).
	.byte 19	#End index (>=0).
	.byte 6	#Initial speed (>=0).
	.byte 17	#Base note index (>=0).

Ep1LevelMusic_Subsong0_Linker:
Ep1LevelMusic_Subsong0_DisarkPointerRegionStart1:
#Position 0
Ep1LevelMusic_Subsong0_Linker_Loop:
	.word Ep1LevelMusic_Subsong0_Track1
	.word Ep1LevelMusic_Subsong0_Track1
	.word Ep1LevelMusic_Subsong0_Track11
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 1
	.word Ep1LevelMusic_Subsong0_Track1
	.word Ep1LevelMusic_Subsong0_Track10
	.word Ep1LevelMusic_Subsong0_Track11
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 2
	.word Ep1LevelMusic_Subsong0_Track1
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 3
	.word Ep1LevelMusic_Subsong0_Track2
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 4
	.word Ep1LevelMusic_Subsong0_Track8
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 5
	.word Ep1LevelMusic_Subsong0_Track5
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 6
	.word Ep1LevelMusic_Subsong0_Track6
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 7
	.word Ep1LevelMusic_Subsong0_Track9
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 8
	.word Ep1LevelMusic_Subsong0_Track8
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 9
	.word Ep1LevelMusic_Subsong0_Track5
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 10
	.word Ep1LevelMusic_Subsong0_Track6
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 11
	.word Ep1LevelMusic_Subsong0_Track7
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track4
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 12
	.word Ep1LevelMusic_Subsong0_Track8
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 13
	.word Ep1LevelMusic_Subsong0_Track5
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 14
	.word Ep1LevelMusic_Subsong0_Track6
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 15
	.word Ep1LevelMusic_Subsong0_Track9
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 16
	.word Ep1LevelMusic_Subsong0_Track8
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 17
	.word Ep1LevelMusic_Subsong0_Track5
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 18
	.word Ep1LevelMusic_Subsong0_Track6
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track3
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

#Position 19
	.word Ep1LevelMusic_Subsong0_Track7
	.word Ep1LevelMusic_Subsong0_Track0
	.word Ep1LevelMusic_Subsong0_Track4
	.word Ep1LevelMusic_Subsong0_LinkerBlock0

Ep1LevelMusic_Subsong0_DisarkPointerRegionEnd1:
	.word 0	#Loop.
Ep1LevelMusic_Subsong0_DisarkWordForceReference2:
	.word Ep1LevelMusic_Subsong0_Linker_Loop

Ep1LevelMusic_Subsong0_LinkerBlock0:
	.byte 32	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
Ep1LevelMusic_Subsong0_DisarkWordForceReference3:
	.word Ep1LevelMusic_Subsong0_SpeedTrack0	#SpeedTrack address.
Ep1LevelMusic_Subsong0_DisarkWordForceReference4:
	.word Ep1LevelMusic_Subsong0_EventTrack0	#EventTrack address.

Ep1LevelMusic_Subsong0_Track0:
	.byte 135
	.byte 1	#New Instrument (1).
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 2	#New Instrument (2).
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 1	#New Instrument (1).
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 2	#New Instrument (2).
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 1	#New Instrument (1).
	.byte 7
	.byte 60	#Waits for 1 line.

	.byte 7
	.byte 7
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 2	#New Instrument (2).
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 1	#New Instrument (1).
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 2	#New Instrument (2).
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 1	#New Instrument (1).
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 2	#New Instrument (2).
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 1	#New Instrument (1).
	.byte 7
	.byte 60	#Waits for 1 line.

	.byte 7
	.byte 7
	.byte 60	#Waits for 1 line.

	.byte 135
	.byte 2	#New Instrument (2).
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track1:
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track2:
	.byte 124	#No note, but effects.
	.byte 9	#Index to an effect block.
	.byte 61, 22	#Waits for 23 lines.

	.byte 247
	.byte 6	#New Instrument (6).
	.byte 1	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 7	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 8	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 3	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 4	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 5	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 6	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track3:
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 149
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 152
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 151
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 149
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 19
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 148
	.byte 5	#New Instrument (5).
	.byte 18
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 145
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track4:
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 149
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 149
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 152
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 151
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 147
	.byte 5	#New Instrument (5).
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 247
	.byte 6	#New Instrument (6).
	.byte 1	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 7	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 8	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 3	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 4	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 5	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 6	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track5:
	.byte 213
	.byte 4	#New Instrument (4).
	.byte 2	#Index to an effect block.
	.byte 61, 6	#Waits for 7 lines.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 21
	.byte 61, 6	#Waits for 7 lines.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 24
	.byte 60	#Waits for 1 line.

	.byte 23
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track6:
	.byte 149
	.byte 4	#New Instrument (4).
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 20
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 23
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 20
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 24
	.byte 25
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track7:
	.byte 149
	.byte 4	#New Instrument (4).
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 20
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 23
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 20
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 26
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 23
	.byte 60	#Waits for 1 line.

	.byte 24
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track8:
	.byte 213
	.byte 4	#New Instrument (4).
	.byte 2	#Index to an effect block.
	.byte 61, 6	#Waits for 7 lines.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 62 + 2 * 64	#Optimized wait for 4 lines.

	.byte 21
	.byte 61, 6	#Waits for 7 lines.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 24
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track9:
	.byte 149
	.byte 4	#New Instrument (4).
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 20
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 23
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 20
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 25
	.byte 24
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track10:
	.byte 61, 23	#Waits for 24 lines.

	.byte 135
	.byte 2	#New Instrument (2).
	.byte 7
	.byte 60	#Waits for 1 line.

	.byte 7
	.byte 7
	.byte 60	#Waits for 1 line.

	.byte 7
	.byte 61, 127	#Waits for 128 lines.


Ep1LevelMusic_Subsong0_Track11:
	.byte 211
	.byte 5	#New Instrument (5).
	.byte 2	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 24
	.byte 60	#Waits for 1 line.

	.byte 23
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 21
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 20
	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 17
	.byte 61, 127	#Waits for 128 lines.


#The speed tracks
Ep1LevelMusic_Subsong0_SpeedTrack0:
	.byte 255	#Wait for 128 lines.

#The event tracks
Ep1LevelMusic_Subsong0_EventTrack0:
	.byte 255	#Wait for 128 lines.

Ep1LevelMusic_Subsong0_DisarkByteRegionEnd0:
